StoreFrontLab.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFrontLab.DATA.EF;
using StoreFrontLab.UI.MVC.Models;

namespace StoreFrontLab.UI.MVC.Controllers
{
    public class ProductsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.ProductType1).Include(p => p.Vendor);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ProductType = new SelectList(db.ProductTypes, "ProductType1", "TypeName");
            ViewBag.VendorID = new SelectList(db.Vendors, "VendorID", "VendorName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,ProductType,Description,Price,ProductImage,VendorID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductType = new SelectList(db.ProductTypes, "ProductType1", "TypeName", product.ProductType);
            ViewBag.VendorID = new SelectList(db.Vendors, "VendorID", "VendorName", product.VendorID);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductType = new SelectList(db.ProductTypes, "ProductType1", "TypeName", product.ProductType);
            ViewBag.VendorID = new SelectList(db.Vendors, "VendorID", "VendorName", product.VendorID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,ProductType,Description,Price,ProductImage,VendorID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductType = new SelectList(db.ProductTypes, "ProductType1", "TypeName", product.ProductType);
            ViewBag.VendorID = new SelectList(db.Vendors, "VendorID", "VendorName", product.VendorID);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //POST: add to cart
        [HttpPost]
        public ActionResult AddToCart(int qty, int productID)
        {
            //Create the shell local shopping
            Dictionary<int, ShoppingCartViewModel> shoppingCart = null;

            //Check the global shopping cart
            if (Session["cart"] != null)
            {
                //if it has stuff in it, reassing to the local
                shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];
            }
            else
            {
                //create an empty local version
                shoppingCart = new Dictionary<int, ShoppingCartViewModel>();
            }

            //get the product being displayed in the view
            Product product = db.Products.Where(x => x.ProductID == productID).FirstOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }

            else
            {
                //product is valid
                ShoppingCartViewModel item = new ShoppingCartViewModel(qty, product);
                //if the item is already in the cart just increase the qty
                if (shoppingCart.ContainsKey(product.ProductID))
                {
                    shoppingCart[product.ProductID].Qty += qty;
                }
                else//add item to cart
                {
                    shoppingCart.Add(product.ProductID, item);
                }
                //update session cart with new item/qty
                Session["cart"] = shoppingCart;

                Session["confirm"] = string.Format($"{qty} {product.ProductName} " + $"{ ((qty > 1) ? "were" : "was")} added to your cart.");
            }
            return RedirectToAction("Index", "ShoppingCart");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFrontLab.UI.MVC/Controllers/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFrontLab.DATA.EF;
using PagedList;
using PagedList.Mvc;

namespace StoreFrontLab.UI.MVC.Controllers
{
    public class VendorsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Vendors
        public ActionResult Index(int page = 1)
        {
            int pageSize = 7;
            var vendors = db.Vendors.ToList();
            return View(vendors.ToPagedList(page, pageSize));
        }

        // GET: Vendors/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendors.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // GET: Vendors/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "VendorID,VendorName,ContactName,PhoneNumber")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Vendors.Add(vendor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vendor);
        }

        // GET: Vendors/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendors.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "VendorID,VendorName,ContactName,PhoneNumber")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vendor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vendor);
        }

        // GET: Vendors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendor vendor = db.Vendors.Find(id);
            if (vendor == null)
            {
                return HttpNotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vendor vendor = db.Vendors.Find(id);
            db.Vendors.Remove(vendor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFrontLab.UI.MVC/Views/Shared/2ndLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    <!--
    Classic Template
    http://www.templatemo.com/tm-488-classic
    -->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="~/content/css/bootstrap.min.css">                        <!-- Bootstrap style -->
    <link rel="stylesheet" href="~/content/css/templatemo-style.css">                     <!-- Templatemo style -->
    <link type="text/css" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" /> <!--datatables.net-->
    <link href="~/Content/css/custom.css" rel="stylesheet" />
    <!--Paged list-->
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>

<body>

    <div class="tm-header custom-header">
        <div class="container-fluid">
            <div class="tm-header-inner">
                <a href="#" class="navbar-brand tm-site-name">Classic</a>

                <!-- navbar -->
                <nav class="navbar tm-main-nav">

                    <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                        &#9776;
                    </button>

                    <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("About", "Home")" class="nav-link">About</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Contact", "Home")" class="nav-link">Contact</a>
                            </li>
                            @*@if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
                                }*@
                            @Html.Partial("_LoginPartial")
                        </ul>

                    </div>

                </nav>

            </div>
        </div>
    </div>
    <!-- Sidebar -->
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <!-- Admin Button -->
        <div id="admin-btn" class="button" onclick="openAdminNav()">
            <span class="verticle-text">ADMIN</span>
        </div>

        <!-- Admin Navigation -->
        <div id="admin-nav" class="sidenav">
            <a href="javascript:void(0)" class="close-btn" onclick="closeAdminNav()">&times;</a>
            @Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })
            @Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })

        </div>
    }
    <!-- Featured Posts -->
    <main>
        @RenderBody()
    </main>


    <footer class="tm-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 tm-copyright-col">
                    <p class="tm-copyright-text">Copyright @DateTime.Now.Year Your Company Name</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- load JS files -->
    <script src="~/content/js/jquery-1.11.3.min.js"></script>             <!-- jQuery (https://jquery.com/download/) -->
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h -->
    <script src="~/content/js/bootstrap.min.js"></script>   <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
    <script type="text/javascript" src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            //Below we selected all anchor tags in the navigation menu and run an anonymous function.
            $('.navbar-nav li.nav-item').each(function () {
                //Look at the href for the a tag and compare it to the location of the HTTP request in the URL. If the path of a specific view matches the path in the browser, run the code in the if statement
                if ($(this).find('a').attr('href') == window.location.pathname) {
                    //Add the class of active to the a tag that matches the window.location.pathname
                    $(this).addClass('active');
                }
            });
        });

        //Toggle Admin Menu

        function openAdminNav() {
            document.getElementById('admin-btn').style.display = "none";
            document.getElementById('admin-nav').style.width = "250px";
        }

        function closeAdminNav() {
            document.getElementById('admin-btn').style.display = "block";
            document.getElementById('admin-nav').style.width = "0";
        }

    </script>

</body>
</html>

StoreFrontLab.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Web App for thrift store product managment">
    <meta name="author" content="Jacob Filer">
    <title>Clean Blog - Start Bootstrap Theme</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/NewContent/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Content/NewContent/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    <link href="~/Content/NewContent/css/clean-blog.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/css/custom.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="index.html">Bargin Basement</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Products")" class="nav-link">Products</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Vendors")" class="nav-link">Vendors</a>
                    </li>
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!-- Sidebar -->
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        <!-- Admin Button -->
        <div id="admin-btn" class="button" onclick="openAdminNav()">
            <span class="verticle-text">ADMIN</span>
        </div>

        <!-- Admin Navigation -->
        <div id="admin-nav" class="sidenav">
            <a href="javascript:void(0)" class="close-btn" onclick="closeAdminNav()">&times;</a>
            @Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })
            @Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })

        </div>
    }
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('/Content/NewContent/img/home-bg.jpg')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 mx-auto">
                @RenderBody()
                <!-- Pager -->
                <div class="clearfix">

                </div>
            </div>
        </div>
    </div>
    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/jacob-filer/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/jacobfiler" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy;Jacob Filer 2020</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/NewContent/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/NewContent/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Content/NewContent/js/clean-blog.min.js"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
</body>
</html>


@RenderSection("scripts", required: false)
<script>
    function openAdminNav() {
        document.getElementById('admin-btn').style.display = "none";
        document.getElementById('admin-nav').style.width = "250px";
    }

    function closeAdminNav() {
        document.getElementById('admin-btn').style.display = "block";
        document.getElementById('admin-nav').style.width = "0";
    }
</script>

StoreFrontLab.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>